#!/usr/bin/env groovy
@Library('sgsdk-live-personal') _

pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(
            daysToKeepStr: '15'
        ))
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'TARGET_ENV',
            choices: getEnvChoices(),
            description: 'The environment to deploy to.')
    }
    stages {
        stage('Deploy') {
            steps {
                levantDeploy job: 'example', env: params.TARGET_ENV, useNomadRun: true
            }
        }
    }
}
